#!/usr/bin/env python3
"""
mkassets.py - generate the test asset files and the C table to verify them.

Each file is filled with deterministic pseudo random data; the header written
for the Atari program holds name, size and a Fletcher-16 style checksum
(sum1 += b; sum2 += sum1, both 8 bit) that the program recomputes after
the load.

usage: mkassets.py outdir header.h size [size ...]
       size in bytes, 2048..16384
"""
import os
import random
import sys


def checksum(data):
    s1 = s2 = 0
    for b in data:
        s1 = (s1 + b) & 0xFF
        s2 = (s2 + s1) & 0xFF
    return (s2 << 8) | s1


def main():
    if len(sys.argv) < 4:
        sys.stderr.write("usage: mkassets.py outdir header.h size [size ...]\n")
        sys.exit(1)
    outdir, header = sys.argv[1], sys.argv[2]
    sizes = [int(s, 0) for s in sys.argv[3:]]
    os.makedirs(outdir, exist_ok=True)

    rows = []
    for n, size in enumerate(sizes):
        if not 2048 <= size <= 16384:
            sys.stderr.write("mkassets: size %d out of 2K..16K range\n" % size)
            sys.exit(1)
        base = "T%02dK%d" % ((size + 1023) // 1024, n)
        rng = random.Random(0x5EED + n)
        data = bytes(rng.getrandbits(8) for _ in range(size))
        open(os.path.join(outdir, base + ".DAT"), "wb").write(data)
        name83 = base.ljust(8) + "DAT"
        rows.append('\t{ "%s", %5d, 0x%04X },' % (name83, size, checksum(data)))

    with open(header, "w") as h:
        h.write("/* generated by mkassets.py - do not edit */\n")
        h.write("#ifndef __ASSETS_H__\n#define __ASSETS_H__\n\n")
        h.write("typedef struct {\n\tconst char *name83;\n\tunsigned int size;\n"
                "\tunsigned int sum;\n} asset_t;\n\n")
        h.write("#define ASSET_MAXSIZE %d\n" % max(sizes))
        h.write("#define ASSET_COUNT %d\n\n" % len(sizes))
        h.write("static const asset_t assets[ASSET_COUNT] = {\n")
        h.write("\n".join(rows) + "\n};\n\n#endif\n")


if __name__ == "__main__":
    main()
