#!/usr/bin/env python3
"""
mkassets.py - put the asset files on the disk directory and write the C table
used by the test program to verify them.

Two kinds of assets:
  --sizes N ...   generated test files (deterministic pseudo random data),
                  N bytes each, 2048..16384, named TnnKi.DAT
  --files F ...   user files, copied as they are (name converted to upper
                  case, it must already be a valid DOS 8.3 name)

The header holds name (8.3, blank padded, no dot), size and a Fletcher-16
style checksum (sum1 += b; sum2 += sum1, both 8 bit) that the program
recomputes after every load.

usage: mkassets.py --out DIR --header FILE [--sizes N ...] [--files F ...]
"""
import argparse
import os
import random
import re
import sys

MAXSIZE = 16384                         # load buffer of the test program
RESERVED = {"PICODOS.SYS"}
NAME_RE = re.compile(r"^([A-Z][A-Z0-9]{0,7})(?:\.([A-Z0-9]{0,3}))?$")


def die(msg):
    sys.stderr.write("mkassets: %s\n" % msg)
    sys.exit(1)


def checksum(data):
    s1 = s2 = 0
    for b in data:
        s1 = (s1 + b) & 0xFF
        s2 = (s2 + s1) & 0xFF
    return (s2 << 8) | s1


def dos_name(path):
    """host file name -> (NAME.EXT, 11 chars directory name)"""
    base = os.path.basename(path).upper()
    m = NAME_RE.match(base)
    if not m:
        die("%s: not a valid DOS 8.3 name (letter + up to 7 letters/digits, "
            "extension up to 3 letters/digits)" % path)
    name, ext = m.group(1), m.group(2) or ""
    return (name + "." + ext if ext else name), name.ljust(8) + ext.ljust(3)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--header", required=True)
    ap.add_argument("--sizes", nargs="*", default=[])
    ap.add_argument("--files", nargs="*", default=[])
    ap.add_argument("--reserved", nargs="*", default=[],
                    help="names already on the disk (the program)")
    args = ap.parse_args()

    assets = []                         # (dosname, name83, data)
    for n, s in enumerate(args.sizes):
        size = int(s, 0)
        if not 2048 <= size <= MAXSIZE:
            die("test asset size %d out of 2048..%d range" % (size, MAXSIZE))
        base = "T%02dK%d.DAT" % ((size + 1023) // 1024, n)
        rng = random.Random(0x5EED + n)
        data = bytes(rng.getrandbits(8) for _ in range(size))
        assets.append((base, dos_name(base)[1], data))

    for f in args.files:
        if not os.path.isfile(f):
            continue
        dosname, name83 = dos_name(f)
        data = open(f, "rb").read()
        if not 1 <= len(data) <= MAXSIZE:
            die("%s: %d bytes, the test buffer takes 1..%d" % (f, len(data), MAXSIZE))
        assets.append((dosname, name83, data))

    if not assets:
        die("no assets: set ASSET_SIZES and/or put files in the assets directory")
    if len(assets) > 64:
        die("%d files: a DOS 2 directory holds 64 (minus the program)" % len(assets))

    seen = RESERVED | {r.upper() for r in args.reserved}
    for dosname, _, _ in assets:
        if dosname in seen:
            die("duplicate or reserved file name %s" % dosname)
        seen.add(dosname)

    os.makedirs(args.out, exist_ok=True)
    rows = []
    for dosname, name83, data in assets:
        open(os.path.join(args.out, dosname), "wb").write(data)
        rows.append('\t{ "%s", %5d, 0x%04X },' % (name83, len(data), checksum(data)))

    sectors = sum((len(d) + 124) // 125 for _, _, d in assets)
    sys.stderr.write("mkassets: %d assets, %d bytes, %d data sectors\n"
                     % (len(assets), sum(len(d) for _, _, d in assets), sectors))

    with open(args.header, "w") as h:
        h.write("/* generated by mkassets.py - do not edit */\n")
        h.write("#ifndef __ASSETS_H__\n#define __ASSETS_H__\n\n")
        h.write("typedef struct {\n\tconst char *name83;\n\tunsigned int size;\n"
                "\tunsigned int sum;\n} asset_t;\n\n")
        h.write("#define ASSET_MAXSIZE %d\n" % max(len(d) for _, _, d in assets))
        h.write("#define ASSET_COUNT %d\n\n" % len(assets))
        h.write("static const asset_t assets[ASSET_COUNT] = {\n")
        h.write("\n".join(rows) + "\n};\n\n#endif\n")


if __name__ == "__main__":
    main()
