#!/usr/bin/env python3
"""
mksidtab.py - SID frequency tables for src/sidrmt.s

    python3 tools/mksidtab.py build/sidtab.s

For the usual POKEY setting (64 kHz clock, 8 bit channel) the SID frequency
of a POKEY channel depends only on AUDF and on the kind of sound, so it is
read from a table instead of being divided every frame:

    Fn = K / n,  n = 28 * (AUDF + 1) machine cycles,
    K  = POKEY clock * 2^24 / C64 clock / m

    kind 0  pure tone          m = 2
    kind 1  distortion C       m = 15, 5 or 3: period of poly4 sampled every
                               n cycles (n mod 15); n mod 15 = 0 -> 0 (silent)
    kind 2  poly5 tone         m = 31
    kind 3  poly17 noise       m = 16 (SID noise shifts at 16 x the oscillator)
    kind 4  poly5 noise        m = 32

The values are for PAL (POKEY 1773447 Hz, C64 985248 Hz); on NTSC sidrmt.s
scales them once at start-up (x 0.9727, POKEY 1789790 Hz, C64 1022727 Hz).
Layout: sidtab_lo = 5 pages (kind * 256 + AUDF), then sidtab_hi = 5 pages.
"""
import math
import sys

POKEY, C64 = 1773447, 985248
C = POKEY * 2 ** 24 / C64


def fn(kind, audf):
    n = 28 * (audf + 1)
    if kind == 1:
        g = math.gcd(n % 15, 15) if n % 15 else 15
        if g == 15:
            return 0
        m = 15 // g
    else:
        m = {0: 2, 2: 31, 3: 16, 4: 32}[kind]
    return min(65535, round(C / m / n))


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: mksidtab.py output.s")
    vals = [fn(k, a) for k in range(5) for a in range(256)]
    out = ["; generated by tools/mksidtab.py - do not edit",
           "; SID Fn for POKEY 64 kHz 8 bit channels, PAL; kind * 256 + AUDF",
           "        .export sidtab_lo, sidtab_hi",
           '        .segment "SIDTAB"',
           "sidtab_lo:"]
    for part in (lambda v: v & 0xFF, lambda v: v >> 8):
        if part(0x1234) == 0x12:
            out.append("sidtab_hi:")
        for i in range(0, len(vals), 16):
            out.append("        .byte " + ",".join("$%02X" % part(v) for v in vals[i:i + 16]))
    with open(sys.argv[1], "w") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
