#!/usr/bin/env python3
"""
rmt2ca65.py - convert an RMT4 (mono) module into a relocatable ca65 source.

An .rmt file is an Atari binary file ($FFFF header) whose first block holds
the module assembled at a fixed address (usually $4000), full of absolute
pointers. This tool rewrites every pointer as "rmt_song + offset", so the
linker can place the module anywhere.

Pointers relocated:
  - header: instruments table, tracks lo table, tracks hi table, song
  - instruments table (words, 0 = unused instrument)
  - tracks lo/hi tables (split bytes, 0 = unused track)
  - song "goto" lines: $FE, xx, lo, hi

usage: rmt2ca65.py input.rmt output.s [label]
"""
import struct
import sys


def die(msg):
    sys.stderr.write("rmt2ca65: %s\n" % msg)
    sys.exit(1)


def main():
    if len(sys.argv) < 3:
        die("usage: rmt2ca65.py input.rmt output.s [label]")
    src, dst = sys.argv[1], sys.argv[2]
    label = sys.argv[3] if len(sys.argv) > 3 else "_rmt_song"

    raw = open(src, "rb").read()
    if raw[:2] != b"\xff\xff":
        die("%s: not an Atari binary file" % src)
    start, end = struct.unpack("<HH", raw[2:6])
    data = raw[6:6 + end - start + 1]
    if len(data) != end - start + 1:
        die("%s: truncated module block" % src)
    if data[:4] == b"RMT8":
        die("%s: stereo RMT8 module, the player is built mono (RMT4)" % src)
    if data[:4] != b"RMT4":
        die("%s: not an RMT4 module" % src)

    def word(off):
        return data[off] | (data[off + 1] << 8)

    def inmod(ptr):
        return start <= ptr <= end

    words = {}    # offset -> target offset (16 bit pointer)
    lobytes = {}  # offset -> target offset (low byte)
    hibytes = {}  # offset -> target offset (high byte)

    p_instr, p_tlo, p_thi, p_song = (word(o) for o in (8, 10, 12, 14))
    for o in (8, 10, 12, 14):
        if not inmod(word(o)):
            die("header pointer at +%d out of module" % o)
        words[o] = word(o) - start

    o_instr, o_tlo, o_thi, o_song = (p - start for p in (p_instr, p_tlo, p_thi, p_song))

    for off in range(o_instr, o_tlo, 2):
        ptr = word(off)
        if ptr == 0:
            continue
        if not inmod(ptr):
            die("instrument pointer at +%d out of module ($%04X)" % (off, ptr))
        words[off] = ptr - start

    ntracks = o_thi - o_tlo
    for t in range(ntracks):
        ptr = data[o_tlo + t] | (data[o_thi + t] << 8)
        if ptr == 0:
            continue
        if not inmod(ptr):
            die("track %d pointer out of module ($%04X)" % (t, ptr))
        lobytes[o_tlo + t] = ptr - start
        hibytes[o_thi + t] = ptr - start

    off = o_song
    while off + 3 < len(data):
        if data[off] == 0xFE:
            ptr = word(off + 2)
            if not inmod(ptr):
                die("song goto at +%d out of module ($%04X)" % (off, ptr))
            words[off + 2] = ptr - start
        off += 4

    out = []
    out.append("; generated by rmt2ca65.py from %s - do not edit" % src)
    out.append("; original address $%04X-$%04X, %d bytes, speed %d, instr speed %d"
               % (start, end, len(data), data[5], data[6]))
    out.append("")
    out.append("        .export %s" % label)
    out.append("        .segment \"RODATA\"")
    out.append("%s:" % label)
    i = 0
    line = []

    def flush():
        if line:
            out.append("        .byte " + ",".join(line))
            line.clear()

    while i < len(data):
        if i in words:
            flush()
            out.append("        .word %s+$%04X" % (label, words[i]))
            i += 2
            continue
        if i in lobytes:
            flush()
            out.append("        .byte <(%s+$%04X)" % (label, lobytes[i]))
        elif i in hibytes:
            flush()
            out.append("        .byte >(%s+$%04X)" % (label, hibytes[i]))
        else:
            line.append("$%02X" % data[i])
            if len(line) == 16:
                flush()
        i += 1
    flush()
    out.append("")

    open(dst, "w").write("\n".join(out))
    sys.stderr.write("rmt2ca65: %s -> %s (%d bytes, %d relocations, instr speed %d)\n"
                     % (src, dst, len(data), len(words) + len(lobytes) + len(hibytes), data[6]))
    if data[6] != 1:
        sys.stderr.write("rmt2ca65: WARNING instrument speed %d: the VBI calls the player once per frame\n" % data[6])


if __name__ == "__main__":
    main()
