#!/usr/bin/env python3
"""
rmtinfo.py - song name, author, date and song length of an RMT module, as a
C header for src/rmtplay.c (from VERA_ATARI_PBI vera-tests/rmt/tools).

Like the SAP export of Raster Music Tracker (NAME / AUTHOR / DATE tags), the
player shows three lines. They come from the text RMT stores in the second
block of the .rmt file (song name, then the instrument names), for example

    "gem'x song, Atari version by raster/c.p.u. 2004"

    NAME   = text before the first ", "        -> "gem'x song"
    AUTHOR = the rest                           -> "Atari version by raster/c.p.u. 2004"
    DATE   = first year (19xx/20xx) in the text, unless AUTHOR already
             shows it (here it does, so DATE stays empty)

A line longer than the 40 characters of the screen is kept whole (up to
MAXLEN characters): the player scrolls it, 5 seconds into the song.

--name / --author / --date override each field (empty = keep the one from
the file). A module without text (tools/mod2rmt4.py) gets
its file name as NAME.

RMT_INFO_LINES is the number of song lines, without a final "goto" line.

usage: rmtinfo.py input.rmt output.h [--name S] [--author S] [--date S]
"""
import argparse
import os
import re
import struct
import sys

MAXLEN = 200    # longest line kept (the player keeps length + 40 blanks in a byte)


def die(msg):
    sys.stderr.write("rmtinfo: %s\n" % msg)
    sys.exit(1)


def blocks(raw):
    """Blocks of an Atari binary file: (start, data)."""
    out = []
    i = 0
    while i + 4 <= len(raw):
        if raw[i:i + 2] == b"\xff\xff":
            i += 2
            continue
        start, end = struct.unpack("<HH", raw[i:i + 4])
        out.append((start, raw[i + 4:i + 4 + end - start + 1]))
        i += 4 + end - start + 1
    return out


def song_text(b):
    if len(b) < 2:
        return ""
    return b[1][1].split(b"\0")[0].decode("latin-1").strip()


def song_lines(b):
    start, data = b[0]
    if data[:3] != b"RMT":
        die("not an RMT module")
    width = 8 if data[3:4] == b"8" else 4
    song = struct.unpack("<H", data[14:16])[0] - start
    n = (len(data) - song) // width
    if n and data[song + (n - 1) * width] == 0xFE:
        n -= 1                  # goto line
    return n


def c_string(s):
    s = "".join(c if 32 <= ord(c) < 127 else "?" for c in s)[:MAXLEN]
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser(description="RMT song info as a C header")
    ap.add_argument("input")
    ap.add_argument("output")
    ap.add_argument("--name", default="")
    ap.add_argument("--author", default="")
    ap.add_argument("--date", default="")
    a = ap.parse_args()

    raw = open(a.input, "rb").read()
    if raw[:2] != b"\xff\xff":
        die("%s: not an Atari binary file" % a.input)

    b = blocks(raw)
    text = song_text(b)
    lines = song_lines(b)
    name, _, author = text.partition(", ")
    year = re.search(r"\b(19|20)\d\d\b", text)
    name = a.name or name.strip() or os.path.splitext(os.path.basename(a.input))[0]
    author = a.author or author.strip()
    date = a.date
    if not date and year and year.group(0) not in author:
        date = year.group(0)    # not shown twice when the author line has it

    with open(a.output, "w") as f:
        f.write("/* generated by rmtinfo.py from %s - do not edit */\n" % a.input)
        f.write("#define RMT_INFO_NAME   %s\n" % c_string(name))
        f.write("#define RMT_INFO_AUTHOR %s\n" % c_string(author))
        f.write("#define RMT_INFO_DATE   %s\n" % c_string(date))
        f.write("#define RMT_INFO_LINES  %d\n" % lines)
    sys.stderr.write("rmtinfo: %s: NAME=%r AUTHOR=%r DATE=%r, %d song lines\n"
                     % (a.input, name, author, date, lines))


if __name__ == "__main__":
    main()
