;
; File generated by cc65 v 2.19 - Git c720c3c48
;
	.fopt		compiler,"cc65 v 2.19 - Git c720c3c48"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_clrscr
	.import		_kbhit
	.import		_gotoxy
	.import		_cprintf
	.import		_cgetc
	.import		_rmt_song_data
	.import		_sid_init
	.import		_sid_play_on
	.import		_sid_play_off
	.import		_sid_frames
	.import		_sid_volume
	.export		_main

.segment	"RODATA"

S0002:
	.byte	$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D
	.byte	$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D,$3D
	.byte	$0A,$0D,$0A,$0D,$00
S0004:
	.byte	$CD,$55,$53,$49,$43,$20,$53,$54,$41,$52,$54,$45,$44,$20,$28,$C3
	.byte	$C9,$C1,$31,$20,$C9,$D2,$D1,$20,$41,$43,$54,$49,$56,$45,$29,$0A
	.byte	$0D,$0A,$0D,$00
S0006:
	.byte	$D0,$4C,$41,$59,$49,$4E,$47,$20,$33,$2D,$43,$48,$41,$4E,$4E,$45
	.byte	$4C,$20,$D3,$C9,$C4,$20,$41,$55,$44,$49,$4F,$2E,$2E,$2E,$0A,$0D
	.byte	$0A,$0D,$00
S0001:
	.byte	$D2,$CD,$D4,$20,$CD,$55,$53,$49,$43,$20,$D0,$4C,$41,$59,$45,$52
	.byte	$20,$2D,$20,$C3,$4F,$4D,$4D,$4F,$44,$4F,$52,$45,$20,$36,$34,$0A
	.byte	$0D,$00
S0005:
	.byte	$D0,$52,$45,$53,$53,$20,$41,$4E,$59,$20,$4B,$45,$59,$20,$54,$4F
	.byte	$20,$53,$54,$4F,$50,$20,$50,$4C,$41,$59,$42,$41,$43,$4B,$0A,$0D
	.byte	$00
S000A:
	.byte	$D0,$4C,$41,$59,$42,$41,$43,$4B,$20,$44,$55,$52,$41,$54,$49,$4F
	.byte	$4E,$3A,$20,$25,$55,$20,$46,$52,$41,$4D,$45,$53,$0A,$0D,$00
S0003:
	.byte	$D3,$4F,$4E,$47,$20,$4C,$4F,$41,$44,$45,$44,$20,$46,$52,$4F,$4D
	.byte	$20,$D2,$CD,$D4,$20,$4D,$4F,$44,$55,$4C,$45,$0A,$0D,$00
S0008:
	.byte	$C3,$C8,$31,$3A,$25,$D8,$20,$C3,$C8,$32,$3A,$25,$D8,$20,$C3,$C8
	.byte	$33,$3A,$25,$D8,$00
S0009:
	.byte	$CD,$55,$53,$49,$43,$20,$53,$54,$4F,$50,$50,$45,$44,$2E,$0A,$0D
	.byte	$00
S0007:
	.byte	$C6,$52,$41,$4D,$45,$53,$3A,$20,$25,$35,$55,$20,$20,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp4
	jsr     _clrscr
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
	lda     #<(_rmt_song_data)
	ldx     #>(_rmt_song_data)
	jsr     _sid_init
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
	jsr     _sid_play_on
	lda     #<(S0004)
	ldx     #>(S0004)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
	lda     #<(S0005)
	ldx     #>(S0005)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
	lda     #<(S0006)
	ldx     #>(S0006)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
L0002:	jmp     L0005
L0004:	jmp     L0002
L0005:	ldx     #$00
	lda     #$00
	jsr     pusha
	ldx     #$00
	lda     #$08
	jsr     _gotoxy
	lda     #<(S0007)
	ldx     #>(S0007)
	jsr     pushax
	lda     _sid_frames
	ldx     _sid_frames+1
	jsr     pushax
	ldy     #$04
	jsr     _cprintf
	lda     #<(S0008)
	ldx     #>(S0008)
	jsr     pushax
	ldx     #$00
	lda     _sid_volume
	ldx     #$00
	and     #$0F
	jsr     pushax
	ldx     #$00
	lda     _sid_volume+1
	ldx     #$00
	and     #$0F
	jsr     pushax
	ldx     #$00
	lda     _sid_volume+2
	ldx     #$00
	and     #$0F
	jsr     pushax
	ldy     #$08
	jsr     _cprintf
	jsr     _kbhit
	tax
	jeq     L0006
	jsr     _cgetc
	jmp     L0003
L0006:	jmp     L0004
L0003:	jsr     _sid_play_off
	jsr     _clrscr
	lda     #<(S0009)
	ldx     #>(S0009)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
	lda     #<(S000A)
	ldx     #>(S000A)
	jsr     pushax
	lda     _sid_frames
	ldx     _sid_frames+1
	jsr     pushax
	ldy     #$04
	jsr     _cprintf
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

